Make ocamlpack depend on a decent awk instead of bash
Also make configure conform to old versions of sh.

git-svn-id: svn+ssh://scm.gforge.inria.fr/svnroot/mlxxxidl/mlcuddidl/branches/opam-packaging@330 c27d38ec-fa33-0410-b621-fb01b97e5d69

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,8 +2,8 @@
 
 # ---
 
-info () { echo "$1" >/dev/stderr; }
-warn () { echo "$1" >/dev/stderr; }
+info () { echo "$1" >/dev/stderr; return 0; }
+warn () { echo "$1" >/dev/stderr; return 0; }
 err () { echo "$1" >/dev/stderr; exit 1; }
 
 # ---
@@ -11,9 +11,10 @@ err () { echo "$1" >/dev/stderr; exit 1; }
 # Basic test to guess architecture:
 command -v uname >/dev/null || error "Unable to guess ISA!";
 
+out () { echo "$*"; return 0; }
 test_cmd () { command -v $1 >/dev/null; }
 maybe_cmd () { test_cmd $2 && echo "$1 = $2" || warn "$3 seems unavailable"; }
-maybe_cme () { test -z "$4" && maybe_cmd "$@" || echo "$1 = $4"; }
+maybe_cme () { test -z "$4" && maybe_cmd "$@" || out "$1 = $4"; }
 
 # Note we always assume a decent version of gcc here:
 exec 1>"Makefile.config";
@@ -47,9 +48,16 @@ case "${system}" in
 	xcflags="${xcflags} ${free_xcflags}";
 	maybe_cmd "SED" "gsed" "GNU sed";
 	maybe_cmd "M4" "gm4" "GNU m4";
-	maybe_cme "CC" "clang" "LLVM/clang" "$CC";;
+	maybe_cme "CC" "clang" "LLVM/clang" "$CC";
+	# NB: not used actually:
+	maybe_cme "CXX" "clang++" "LLVM/clang++" "$CXX";;
     *)
 	warn "Unknown system: ${system}!";;
 esac;
 
 echo "XCFLAGS = ${xcflags}";
+
+test_cmd awk && {
+    warn "awk not found: documentation will not be built";
+    echo "OCAMLPACK = ./ocamlpack";
+} || true;
