Fix build system for parallel builds

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -30,7 +30,14 @@ EOF
 
 # ---
 
-info () { echo "$@" >/dev/stderr; return 0; }
+info () {
+    if test "x$1" = "x-n"; then
+	shift;
+	echo "$@" | tr -d '\012' >/dev/stderr;
+    else
+	echo "$@" >/dev/stderr;
+    fi
+}
 warn () { echo "$@" >/dev/stderr; return 0; }
 err () { echo "$@" >/dev/stderr; exit 1; }
 arr () { echo "Missing argument for \`$1'!" >/dev/stderr; usage; exit 1; }
@@ -58,58 +65,47 @@ out () { echo "$*"; return 0; }
 assign () { eval "$1=\"$2\""; out "$1 = $2"; }
 test_cmd () { command -v $1 >/dev/null; }
 find_cmd () {
-    # info "test_cmd $1";
-    if test_cmd $1; then
-	cmd=$(command -v $1);
-	test "x$2" != "x" && test "x$2" != "x_" && assign "$2" "$cmd";
-	test "x$3" != "x" && info "$3 found: $cmd" || info "$1 found: $cmd";
-    else
-	test "x$3" != "x" && err "$3 not found" || err "$1 not found";
-    fi
-}
-find_cmdx () {
     v="$1"; shift;
-    if test_cmd $1; then
-	cmd=$(command -v $1);
-	test "x$v" != "x_" && assign "$v" "$cmd";
-	info "$1 found: $cmd";
+    test $# \< 1 && return 1;
+    if test "x$1" = "x"; then
+	shift; find_cmd "$v" "$@";
     else
-	shift;
-	find_cmdx "$v" "$@";
+	info -n "checking for $1... ";
+	if test_cmd $1; then
+	    cmd=$(command -v $1);
+	    test "x$v" != "x_" && assign "$v" "$cmd";
+	    info "yes ($cmd)";
+	else
+	    info "no";
+	    shift; find_cmd "$v" "$@";
+	fi;
     fi;
 }
-maybe_cmd () { find_cmd "$@" || warn "$3 seems unavailable"; }
-maybe_cme () { test "x$4" = "x" && maybe_cmd "$@" || find_cmd "$4" "$2"; }
+find_xcmd () {
+    find_cmd "$@" || {
+	shift;
+	err "one of [$@] is required";
+    }
+}
+find_ocmd () { find_xcmd "$1" "$2.opt" "$2"; }
 
-# Basic test to guess architecture:
-test_cmd uname || err "Unable to guess ISA!";
-
-# Note we always assume a decent version of gcc here:
 exec 1>"Makefile.config";
 cat Makefile.config.in;
 
-system=$(uname -s);
-info "Detected System: ${system}";
-
 # General Utilities
 
-find_cmd mktemp;
-find_cmd ar AR;
-find_cmd ranlib RANLIB;
-find_cmdx SED gsed sed;
-find_cmdx M4 gm4 m4;
-
-if test_cmd awk; then
-    find_cmd awk;
-    info "awk found: documentation will be built";
-    echo "OCAMLPACK = ./ocamlpack";
-else
-    warn "awk not found: documentation will not be built";
-fi
+find_xcmd _ mktemp;
+find_xcmd AR ar;
+find_xcmd RANLIB ranlib;
+find_xcmd SED gsed sed;
+find_xcmd M4 gm4 m4;
+find_xcmd AWK awk;
 
 # OCaml
 
-overs=$(ocamlc -version);
+find_ocmd OCAMLC ocamlc;
+
+overs=$(${OCAMLC} -version);
 case "${overs}" in
     [1-3].* | 4.01.*)
 	err "OCaml version found is ${overs}: OCaml >= 4.02 is required.";;
@@ -117,9 +113,12 @@ case "${overs}" in
 	:;;
 esac
 
-find_cmd ocamlfind OCAMLFIND;
-find_cmd camlidl CAMLIDL;
-find_cmd ocamldep OCAMLDEP;
+find_ocmd OCAMLOPT ocamlopt;
+find_ocmd OCAMLDEP ocamldep;
+find_ocmd OCAMLDOC ocamldoc;
+find_ocmd OCAMLMKLIB ocamlmklib;
+find_xcmd OCAMLFIND ocamlfind;
+find_xcmd CAMLIDL camlidl;
 
 # C
 
@@ -129,32 +128,23 @@ check_compile_args () {
     (
 	cd "${tmpdir}";
 	echo "int main() { return 1; }" > tmp.c;
-	${OCAMLFIND} ocamlopt -ccopt "$*" -c tmp.c 2>&1 >/dev/null || \
+	${OCAMLFIND} ocamlopt -ccopt "$*" -c tmp.c >/dev/null 2>&1 || \
 	    err "not working!";
-	${CC} tmp.o -o a.out 2>&1 >/dev/null || \
+	${CC} tmp.o -o a.out >/dev/null 2>&1 || \
 	    err "not working!";
 	info "working";
     );
     rm -r -f ${tmpdir};
 }
 
-case "${system}" in
-    Linux|Darwin)
-	maybe_cme gcc CC gcc "$CC";
-	maybe_cme g++ CXX g++ "$CXX";;
-    FreeBSD)
-        maybe_cme clang CC "LLVM/clang" "$CC";
-        # NB: not used actually:
-        maybe_cme clang++ CXX "LLVM/clang++" "$CXX";;
-    *)
-        warn "Unknown system: ${system}!";;
-esac
+find_xcmd CC "$CC" gcc clang;
+find_xcmd CXX "$CXX" g++ clang++;
 
 info -n "Checking compilation of C file with ocamlopt: "
 check_compile_args;
 
 if test "x${enable_prof}" = "xyes"; then
-    cprof_flags="$(ocamlc -config | sed -e '/^cc_profile:/!d; s/^[^:]*://;')";
+    cprof_flags="$(${OCAMLC} -config | ${SED} -e '/^cc_profile:/!d; s/^[^:]*://;')";
     info "Profiling flags found: ${cprof_flags}";
     info -n "Checking compilation of C file with ocamlopt -ccopt \"${cprof_flags}\": "
     if check_compile_args "${cprof_flags}"; then
@@ -163,10 +153,18 @@ if test "x${enable_prof}" = "xyes"; then
 	echo "CPROF_FLAGS = ${cprof_flags}";
     else
 	warn "Profiling-enabled version will not be built";
+	echo "ENABLE_PROF = ";	# in case...
     fi;
 else
     info "Profiling-enabled version will not be built (as requested)";
     echo "ENABLE_PROF = ";	# in case...
+fi;
+
+if test "x${AWK}" != "x"; then
+    info "awk found: documentation will be built";
+    echo "OCAMLPACK = ./ocamlpack";
+else
+    warn "awk not found: documentation will not be built";
 fi;
 
 # NB: Ugly hack to avoid weird errors with auto{conf,make} and the likes:
