substitute `/dev/stderr' with `1>&2' in configure script
That's mostly for macosx.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,14 +34,14 @@ EOF
 info () {
     if test "x$1" = "x-n"; then
 	shift;
-	echo "$@" | tr -d '\012' >/dev/stderr;
+	echo "$@" | tr -d '\012' 1>&2;
     else
-	echo "$@" >/dev/stderr;
+	echo "$@" 1>&2;
     fi
 }
-warn () { echo "$@" >/dev/stderr; return 0; }
-err () { echo "$@" >/dev/stderr; exit 1; }
-arr () { echo "Missing argument for \`$1'!" >/dev/stderr; usage; exit 1; }
+warn () { echo "$@" 1>&2; return 0; }
+err () { echo "$@" 1>&2; exit 1; }
+arr () { echo "Missing argument for \`$1'!" 1>&2; usage; exit 1; }
 arg () { test "x$2" != "x" && echo "$2" || arr "$1"; }
 drg () { d="$(arg "$@")"; test -d "$d" && echo "$d" || \
 		 err "Argument for \`$1' should be an existing directory!"; }
