Upgrading to cudd-3.0.0 + parallel builds
git-svn-id: svn+ssh://scm.gforge.inria.fr/svnroot/mlxxxidl/mlcuddidl/branches/opam-packaging@334 c27d38ec-fa33-0410-b621-fb01b97e5d69

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,12 +1,53 @@
 #!/bin/sh
 
+# ------------------------------------------------------------------------------
+
+# data
+
+cudddir="cudd-3.0.0";
+
+# defaults
+
+prefix="/usr/local";
+
+# usage
+
+usage () {
+    cat <<EOF
+usage: $0 [options]
+where available options are:
+  --prefix <prefix>  Specify installation prefix directory
+                     ("$prefix" by default)
+  --docdir <docdir>  Specify documentation installation directory
+                     ("\$prefix/share/doc" by default)
+  --help             Display this help and exit
+EOF
+    exit 0
+}
+
 # ---
 
 info () { echo "$1" >/dev/stderr; return 0; }
 warn () { echo "$1" >/dev/stderr; return 0; }
 err () { echo "$1" >/dev/stderr; exit 1; }
+arr () { echo "Missing argument for \`$1'!" >/dev/stderr; usage; exit 1; }
+arg () { test "x$2" != "x" && echo "$2" || arr "$1"; }
+drg () { d="$(arg "$@")"; test -d "$d" && echo "$d" || \
+		 err "Argument for \`$1' should be an existing directory!"; }
+
+# arg. parsing
+
+while test $# '>' 0; do
+    case "$1" in
+	--prefix) prefix="$(arg "$1" "$2")"; shift; shift;;
+	-h | --help) usage;;
+	*) warn "Ignoring argument \`$1'!"; shift;;
+    esac;
+done;
 
 # ---
+
+# ( cd "${cudddir}" && ./configure --prefix "${prefix}"; )
 
 # Basic test to guess architecture:
 command -v uname >/dev/null || error "Unable to guess ISA!";
@@ -20,32 +61,15 @@ maybe_cme () { test -z "$4" && maybe_cmd "$@" || out "$1 = $4"; }
 exec 1>"Makefile.config";
 cat Makefile.config.in;
 
-basic_xcflags="-fPIC -mtune=native -DHAVE_IEEE_754";
-free_xcflags="-DBSD -D_GNU_SOURCE";
-x86_xcflags="-malign-double";
-amd64_xcflags="-DSIZEOF_VOID_P=8 -DSIZEOF_LONG=8 -DSIZEOF_INT=4";
-
-arch=$(uname -m);
-info "Detected ISA: ${arch}"; 
-case "${arch}" in
-    i686)  
-	xcflags="${basic_xcflags} ${x86_xcflags}";;
-    amd64|x86_64)
-	xcflags="${basic_xcflags} ${amd64_xcflags}";;
-    *)  
-        warn "Unknown ISA: ${arch}!";;
-esac;
-
 system=$(uname -s);
 info "Detected System: ${system}"; 
 case "${system}" in
     Linux)
-	xcflags="${xcflags} ${free_xcflags}";;
+	:;;
     Darwin)
     	maybe_cmd "SED" "gsed" "GNU sed";
     	maybe_cmd "M4" "gm4" "GNU m4";;
     FreeBSD)
-	xcflags="${xcflags} ${free_xcflags}";
 	maybe_cmd "SED" "gsed" "GNU sed";
 	maybe_cmd "M4" "gm4" "GNU m4";
 	maybe_cme "CC" "clang" "LLVM/clang" "$CC";
@@ -55,9 +79,6 @@ case "${system}" in
 	warn "Unknown system: ${system}!";;
 esac;
 
-echo "XCFLAGS = ${xcflags}";
-
 test_cmd awk && {
-    warn "awk not found: documentation will not be built";
     echo "OCAMLPACK = ./ocamlpack";
-} || true;
+} || warn "awk not found: documentation will not be built";
